--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/04/2024 15:56:23
-- Server version: 5.5.64-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE restart;

--
-- Drop table `frist`
--
DROP TABLE IF EXISTS frist;

--
-- Drop table `frist1`
--
DROP TABLE IF EXISTS frist1;

--
-- Set default database
--
USE restart;

--
-- Create table `frist1`
--
CREATE TABLE frist1 (
  fristname varchar(255) NOT NULL,
  lastname varchar(255) NOT NULL,
  email_adress varchar(255) NOT NULL,
  password varchar(255) NOT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 114,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `frist`
--
CREATE TABLE frist (
  FristName varchar(255) NOT NULL,
  LastName varchar(255) NOT NULL,
  Email_adress varchar(255) NOT NULL,
  password varchar(255) NOT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 141,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table frist1
--
INSERT INTO frist1 VALUES
('Albertino Sete', 'Benjamim', '707200252@ucm.ac.mz', '707200252'),
('Argentina Alberto', 'Cherindza', '707200233@ucm.ac.mz', '707200233'),
('Artur Jorge', 'Araújo', '707200251@ucm.ac.mz', '707200251'),
('Aznar Novais', 'Quitengue', '707200468@ucm.ac.mz', '707200468'),
('Bernazila Francisco', 'Jambaia', '707200471@ucm.ac.mz', '707200471'),
('Calida Orlanddo', 'Reginaldo', '707200213@ucm.ac.mz', '707200213'),
('Charles Matias', 'Cangera', '707200412@ucm.ac.mz', '707200412'),
('Chirley Arnaldo', 'Bongo', '707200361@ucm.ac.mz', '707200361'),
('Cleidy Da Cleonildy ', 'Chibante', '707200465@ucm.ac.mz', '707200465'),
('Duwalé Abílio Vasco', 'Domingos', '707200179@ucm.ac.mz', '707200179'),
('Eliseu Albernaz ', 'Vasco', '707200350@ucm.ac.mz', '707200350'),
('Elsia Freitas', 'Sumine', '707200240@ucm.ac.mz', '707200240'),
('Emilson Luís', 'Manuel', '707200256@ucm.ac.mz', '707200256'),
('Esta Miguel', 'Vasco', '707200062@ucm.ac.mz', '707200062'),
('Eufrasia António João', 'Nota', '707200432@ucm.ac.mz', '707200432'),
('Fahim Afzal Abdul', 'Rahim', '707190473@ucm.ac.mz', '707190473'),
('Farai Chadi Bento', 'Quembo', '707200029@ucm.ac.mz', '707200029'),
('Fernanda Jossefa', 'Moises', '707190238@ucm.ac.mz', '707190238'),
('Luís Francisco ', 'Júnior', '707200180@ucm.ac.mz', '707200180'),
('Lurdes Olimpio', 'Ernesto', '707190535@ucm.ac.mz', '707190535'),
('Madicacha', 'Mandogue', '707200183@ucm.ac.mz', '707200183'),
('Marcela Da Graça ', 'Dias', '707200427@ucm.ac.mz', '707200427'),
('Maria Da Graça Júlio', 'Ferro', '707200500@ucm.ac.mz', '707200500'),
('Mariana Rochael', 'Mustaque', '707200323@ucm.ac.mz', '707200323'),
('Neidy Solange ', 'Comé', '707200393@ucm.ac.mz', '707200393'),
('Nelsa Isaque', 'Muchope', '707200253@ucm.ac.mz', '707200253'),
('First Name', 'Last Name', 'Email Address', 'Password'),
('Omega Tomas', 'Jemusse', '707200384@ucm.ac.mz', '707200384'),
('Paciencia Patiance ', 'Magadzire', '707190165@ucm.ac.mz', '707190165'),
('Pedro Armando', 'Horácio', '707200287@ucm.ac.mz', '707200287'),
('Shelta Manuel ', 'Muchope', '707190583@ucm.ac.mz', '707190583'),
('Sunyza Manso', 'Falume', '707190256@ucm.ac.mz', '707190256'),
('Taimo Orlando', 'Reginaldo', '707200105@ucm.ac.mz', '707200105'),
('Tatiana Da Alia Xavier', 'Zunguze', '707200504@ucm.ac.mz', '707200504'),
('Tatiana Domingos ', 'Pacanate', '707200008@ucm.ac.mz', '707200008'),
('Telma Carlos', 'André', '707200457@ucm.ac.mz', '707200457'),
('Venência Vasco', 'Mucuho', '707200348@ucm.ac.mz', '707200348'),
('VICENTE TOZE', 'VICENTE', '707200306@ucm.ac.mz', '707200306'),
('', '', '', '707200239'),
('', '', '', '707200452'),
('', '', '', '707200472'),
('', '', '', '707200269'),
('', '', '', '707200317'),
('', '', '', '707200337'),
('', '', '', '707200461'),
('', '', '', '707200056'),
('', '', '', '707200437'),
('', '', '', '707200444'),
('', '', '', '707190232'),
('', '', '', '707200392'),
('', '', '', '707200055'),
('', '', '', '707200111'),
('', '', '', '707200201'),
('', '', '', '707180361'),
('', '', '', '707200247'),
('', '', '', '707190280'),
('', '', '', '707200048'),
('', '', '', '707200433'),
('', '', '', '707200174'),
('', '', '', '707200025'),
('', '', '', '707200313'),
('', '', '', '707200328'),
('', '', '', '707200221'),
('', '', '', '707200191'),
('', '', '', '707200447'),
('', '', '', '707200415'),
('', '', '', '707200345'),
('', '', '', '707200258'),
('', '', '', '707200263'),
('', '', '', '707200426'),
('', '', '', '707190112'),
('', '', '', '707200053'),
('', '', '', '707200481'),
('', '', '', '707200408'),
('', '', '', '707190276'),
('', '', '', '707200041'),
('', '', '', '707200506'),
('', '', '', '707190372'),
('', '', '', '707190357'),
('', '', '', '707200507'),
('', '', '', '707200064'),
('', '', '', '707200218'),
('', '', '', '707200204'),
('', '', '', '707200217'),
('', '', '', '707200331'),
('', '', '', '707200031'),
('', '', '', '707180299'),
('', '', '', '707200388'),
('', '', '', '707200117'),
('', '', '', '707190120'),
('', '', '', 'Password'),
('', '', '', '707190579'),
('', '', '', '707200032'),
('', '', '', '707200389'),
('', '', '', '707200049'),
('', '', '', '707200039'),
('', '', '', '707190401'),
('', '', '', '707190511'),
('', '', '', '707200349'),
('', '', '', '707200189'),
('', '', '', '707200220'),
('', '', '', '707200291'),
('', '', '', '707200429'),
('', '', '', '707200354'),
('', '', '', '707200166'),
('', '', '', '707190322'),
('', '', '', '707200026'),
('', '', '', '707170283'),
('', '', '', '707200390'),
('', '', '', '707120327'),
('', '', '', '707200417'),
('', '', '', '707200336'),
('', '', '', '707200435'),
('', '', '', '707190035'),
('', '', '', '707200157'),
('', '', '', '707200301'),
('', '', '', '707200119'),
('', '', '', '707200172'),
('', '', '', '707200252'),
('', '', '', '707200456'),
('', '', '', '707200439'),
('', '', '', '707200068'),
('', '', '', '707200274'),
('', '', '', '707200459'),
('', '', '', '707200225'),
('', '', '', '707200121'),
('', '', '', '707200486'),
('', '', '', '707200235'),
('', '', '', '707200208'),
('', '', '', '707200209'),
('', '', '', '707200131'),
('', '', '', '707200422'),
('', '', '', '707200308'),
('', '', '', '707200360'),
('', '', '', '707190329'),
('', '', '', '707200198'),
('', '', '', '707200229'),
('', '', '', '707200264'),
('', '', '', '707200077'),
('', '', '', '707200436'),
('', '', '', '707200123'),
('', '', '', '707200192'),
('', '', '', '707200058');

-- 
-- Dumping data for table frist
--
INSERT INTO frist VALUES
('', '', '', '707200239'),
('', '', '', '707200452'),
('', '', '', '707200472'),
('', '', '', '707200269'),
('', '', '', '707200317'),
('', '', '', '707200337'),
('', '', '', '707200461'),
('', '', '', '707200056'),
('', '', '', '707200437'),
('', '', '', '707200444'),
('', '', '', '707190232'),
('', '', '', '707200392'),
('', '', '', '707200055'),
('', '', '', '707200111'),
('', '', '', '707200201'),
('', '', '', '707180361'),
('', '', '', '707200247'),
('', '', '', '707190280'),
('', '', '', '707200048'),
('', '', '', '707200433'),
('', '', '', '707200174'),
('', '', '', '707200025'),
('', '', '', '707200313'),
('', '', '', '707200328'),
('', '', '', '707200221'),
('', '', '', '707200191'),
('', '', '', '707200172'),
('', '', '', '707200252'),
('', '', '', '707200456'),
('', '', '', '707200439'),
('', '', '', '707200068'),
('', '', '', '707200274'),
('', '', '', '707200459'),
('', '', '', '707200225'),
('', '', '', '707200121'),
('', '', '', '707200486'),
('', '', '', '707200235'),
('', '', '', '707200208'),
('', '', '', '707200209'),
('', '', '', '707200131'),
('', '', '', '707200422'),
('', '', '', '707200308'),
('', '', '', '707200360'),
('', '', '', '707190329'),
('', '', '', '707200198'),
('', '', '', '707200229'),
('', '', '', '707200264'),
('', '', '', '707200077'),
('', '', '', '707200436'),
('', '', '', '707200123'),
('', '', '', '707200192'),
('', '', '', '707200058'),
('', '', '', '707200239'),
('', '', '', '707200452'),
('', '', '', '707200472'),
('', '', '', '707200269'),
('', '', '', '707200317'),
('', '', '', '707200337'),
('', '', '', '707200461'),
('', '', '', '707200056'),
('', '', '', '707200437'),
('', '', '', '707200444'),
('', '', '', '707190232'),
('', '', '', '707200392'),
('', '', '', '707200055'),
('', '', '', '707200111'),
('', '', '', '707200201'),
('', '', '', '707180361'),
('', '', '', '707200247'),
('', '', '', '707190280'),
('', '', '', '707200048'),
('', '', '', '707200433'),
('', '', '', '707200174'),
('', '', '', '707200025'),
('', '', '', '707200313'),
('', '', '', '707200328'),
('', '', '', '707200221'),
('', '', '', '707200191'),
('Albertino Sete', 'Benjamim', '707200252@ucm.ac.mz', '707200252'),
('Argentina Alberto', 'Cherindza', '707200233@ucm.ac.mz', '707200233'),
('Artur Jorge', 'Araújo', '707200251@ucm.ac.mz', '707200251'),
('Aznar Novais', 'Quitengue', '707200468@ucm.ac.mz', '707200468'),
('Bernazila Francisco', 'Jambaia', '707200471@ucm.ac.mz', '707200471'),
('Calida Orlanddo', 'Reginaldo', '707200213@ucm.ac.mz', '707200213'),
('Charles Matias', 'Cangera', '707200412@ucm.ac.mz', '707200412'),
('Chirley Arnaldo', 'Bongo', '707200361@ucm.ac.mz', '707200361'),
('Cleidy Da Cleonildy ', 'Chibante', '707200465@ucm.ac.mz', '707200465'),
('Duwalé Abílio Vasco', 'Domingos', '707200179@ucm.ac.mz', '707200179'),
('Eliseu Albernaz ', 'Vasco', '707200350@ucm.ac.mz', '707200350'),
('Elsia Freitas', 'Sumine', '707200240@ucm.ac.mz', '707200240'),
('Emilson Luís', 'Manuel', '707200256@ucm.ac.mz', '707200256'),
('Esta Miguel', 'Vasco', '707200062@ucm.ac.mz', '707200062'),
('Eufrasia António João', 'Nota', '707200432@ucm.ac.mz', '707200432'),
('Fahim Afzal Abdul', 'Rahim', '707190473@ucm.ac.mz', '707190473'),
('Farai Chadi Bento', 'Quembo', '707200029@ucm.ac.mz', '707200029'),
('Fernanda Jossefa', 'Moises', '707190238@ucm.ac.mz', '707190238'),
('Luís Francisco ', 'Júnior', '707200180@ucm.ac.mz', '707200180'),
('Lurdes Olimpio', 'Ernesto', '707190535@ucm.ac.mz', '707190535'),
('Madicacha', 'Mandogue', '707200183@ucm.ac.mz', '707200183'),
('Marcela Da Graça ', 'Dias', '707200427@ucm.ac.mz', '707200427'),
('Maria Da Graça Júlio', 'Ferro', '707200500@ucm.ac.mz', '707200500'),
('Mariana Rochael', 'Mustaque', '707200323@ucm.ac.mz', '707200323'),
('Neidy Solange ', 'Comé', '707200393@ucm.ac.mz', '707200393'),
('Nelsa Isaque', 'Muchope', '707200253@ucm.ac.mz', '707200253'),
('First Name', 'Last Name', 'Email Address', 'Password'),
('Omega Tomas', 'Jemusse', '707200384@ucm.ac.mz', '707200384'),
('Paciencia Patiance ', 'Magadzire', '707190165@ucm.ac.mz', '707190165'),
('Pedro Armando', 'Horácio', '707200287@ucm.ac.mz', '707200287'),
('Shelta Manuel ', 'Muchope', '707190583@ucm.ac.mz', '707190583'),
('Sunyza Manso', 'Falume', '707190256@ucm.ac.mz', '707190256'),
('Taimo Orlando', 'Reginaldo', '707200105@ucm.ac.mz', '707200105'),
('Tatiana Da Alia Xavier', 'Zunguze', '707200504@ucm.ac.mz', '707200504'),
('Tatiana Domingos ', 'Pacanate', '707200008@ucm.ac.mz', '707200008'),
('Telma Carlos', 'André', '707200457@ucm.ac.mz', '707200457'),
('Venência Vasco', 'Mucuho', '707200348@ucm.ac.mz', '707200348'),
('VICENTE TOZE', 'VICENTE', '707200306@ucm.ac.mz', '707200306');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;